# Generated by Django 6.1 on 2026-09-17 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Packaging Project', max_length=255)),
                ('category', models.CharField(choices=[('FOOD_BEVERAGE', 'Food & Beverages (General)'), ('DAIRY', 'Dairy & Milk Products'), ('SNACKS_CONFECTIONERY', 'Snacks & Confectionery'), ('NUTRACEUTICALS', 'Health Supplements & Nutraceuticals'), ('BEVERAGES', 'Packaged Drinking Water & Beverages'), ('COSMETICS', 'Cosmetics & Personal Care'), ('GENERAL_COMMODITY', 'General Packaged Commodity')], default='FOOD_BEVERAGE', max_length=50)),
                ('pack_type', models.CharField(choices=[('POUCH', 'Flexible Pouch / Bag'), ('BOX', 'Carton / Rectangular Box'), ('CYLINDER', 'Cylindrical Bottle / Can'), ('JAR', 'Tub / Jar'), ('TETRA', 'Tetra Pak / Multi-layered Carton')], default='POUCH', max_length=30)),
                ('height_cm', models.FloatField(default=15.0)),
                ('width_cm', models.FloatField(default=10.0)),
                ('depth_cm', models.FloatField(blank=True, default=4.0, null=True)),
                ('diameter_cm', models.FloatField(blank=True, null=True)),
                ('net_quantity', models.FloatField(default=100.0)),
                ('quantity_unit', models.CharField(default='g', max_length=20)),
                ('mrp', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('diet_type', models.CharField(choices=[('VEG', 'Vegetarian (Green Dot)'), ('NON_VEG', 'Non-Vegetarian (Brown Triangle)'), ('NOT_APPLICABLE', 'Not Applicable (Non-food / Commodity)')], default='VEG', max_length=20)),
                ('fssai_license_no', models.CharField(blank=True, default='10021000000000', max_length=30, null=True)),
                ('brand_name', models.CharField(blank=True, default='PureCraft', max_length=150)),
                ('generic_product_name', models.CharField(blank=True, default='Roasted Almonds with Sea Salt', max_length=200)),
                ('manufacturer_name', models.CharField(blank=True, default='PureCraft Foods Pvt. Ltd.', max_length=255)),
                ('manufacturer_address', models.TextField(blank=True, default='Plot No. 42, Food Park, Phase 1, Gurgaon, Haryana - 122001, India')),
                ('packer_details', models.TextField(blank=True, null=True)),
                ('country_of_origin', models.CharField(default='India', max_length=100)),
                ('consumer_care_email', models.EmailField(default='care@purecraft.in', max_length=254)),
                ('consumer_care_phone', models.CharField(default='+91-1800-111-2222', max_length=50)),
                ('consumer_care_contact', models.TextField(blank=True, default='Manager - Consumer Redressal, PureCraft Foods, Plot 42, Food Park, Gurgaon')),
                ('ingredients', models.TextField(blank=True, default='Almonds (96%), Edible Vegetable Oil (Sunflower), Edible Common Salt (Sea Salt 1.5%), Natural Rosemary Extract.')),
                ('marketing_claims', models.TextField(blank=True, default='High Protein, Zero Trans Fat, No Added Sugar, 100% Natural')),
                ('shelf_life_months', models.IntegerField(default=6)),
                ('primary_color', models.CharField(default='#073b70', max_length=20)),
                ('accent_color', models.CharField(default='#f59e0b', max_length=20)),
                ('bg_color', models.CharField(default='#073b70', max_length=20)),
                ('theme_preset', models.CharField(default='MODERN_NAVY', max_length=30)),
                ('finish_type', models.CharField(default='MATTE', max_length=30)),
                ('hero_image_url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdp_area_sqcm', models.FloatField(default=0.0)),
                ('min_font_size_mm', models.FloatField(default=1.0)),
                ('min_numeral_size_mm', models.FloatField(default=2.0)),
                ('veg_symbol_size_mm', models.FloatField(default=3.0)),
                ('unit_sale_price_text', models.CharField(blank=True, max_length=100)),
                ('spec_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='package_designer.packagingproject')),
            ],
        ),
        migrations.CreateModel(
            name='DesignChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='package_designer.packagingproject')),
            ],
        ),
    ]
