# Generated by Django 6.1 on 2026-09-04 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='product_scans/')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedLabelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_ocr_text', models.TextField()),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('nutritional_info', models.JSONField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('fssai_license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='products.productscan')),
            ],
        ),
    ]
