# Generated by Django 6.1.1 on 2026-09-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedlabeldata',
            name='additives_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedlabeldata',
            name='consumer_contact_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedlabeldata',
            name='expiry_date_raw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extractedlabeldata',
            name='manufacturer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedlabeldata',
            name='manufacturer_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedlabeldata',
            name='manufacturing_date_raw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extractedlabeldata',
            name='mrp_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extractedlabeldata',
            name='mrp_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedlabeldata',
            name='net_quantity_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extractedlabeldata',
            name='net_quantity_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='extractedlabeldata',
            name='net_quantity_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedlabeldata',
            name='product_name_declared',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productscan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('NEEDS_MORE_IMAGES', 'Needs More Images'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_scans/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productscan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
