# Generated by Django 6.0.6 on 2026-09-06 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscan',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productscan',
            name='violations_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScanViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='products.productscan')),
            ],
        ),
    ]
