# Generated by Django 6.1.1 on 2026-09-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_extractedlabeldata_additives_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedlabeldata',
            name='batch_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedlabeldata',
            name='expiry_date_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedlabeldata',
            name='fssai_license_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedlabeldata',
            name='manufacturing_date_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedlabeldata',
            name='mrp_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedlabeldata',
            name='net_quantity_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedlabeldata',
            name='product_name_declared',
            field=models.TextField(blank=True, null=True),
        ),
    ]