# Generated by Django 6.1 on 2026-09-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productscan_extracted_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscan',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='productscan',
            name='violations_summary',
        ),
        migrations.AddField(
            model_name='productscan',
            name='report_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productscan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant')], default='PENDING', max_length=20),
        ),
    ]
