# Generated by Django 6.1 on 2026-09-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productscan_extracted_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanviolation',
            name='severity',
            field=models.CharField(default='High', max_length=50),
        ),
        migrations.DeleteModel(
            name='ExtractedLabelData',
        ),
    ]
