# Generated by Django 6.1.1 on 2026-09-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_extractedlabeldata_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedlabeldata',
            name='labeled_lines_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]