# Generated by Django 6.1.1 on 2026-09-18 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_extractedlabeldata labeled lines json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('NEEDS_MORE_IMAGES', 'Needs More Images')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ScanViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='High', max_length=50)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='products.productscan')),
            ],
        ),
    ]
