# Generated by Django 6.1 on 2026-09-12 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('complaint_type', models.CharField(choices=[('consumer', 'Consumer Complaint'), ('company', 'Company Complaint')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('product_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('violation_category', models.CharField(choices=[('mrp', 'MRP'), ('net_quantity', 'Net Quantity'), ('manufacturer', 'Manufacturer Details'), ('consumer_care', 'Consumer Care Details'), ('date', 'Date'), ('country_origin', 'Country of Origin'), ('other', 'Other')], max_length=30)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='complaint_evidence/')),
                ('scan_report', models.FileField(blank=True, null=True, upload_to='scan_reports/')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('resolution_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]