# Generated by Django 6.1 on 2026-09-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='created_at',
            new_name='submitted',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_type',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='id',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='location',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='resolution_remarks',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='scan_report',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.AddField(
            model_name='complaint',
            name='compliance_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='parakh_evidence/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='violation_category',
            field=models.CharField(max_length=200),
        ),
    ]
