# Generated by Django 6.1 on 2026-09-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_rename_created_at_complaint_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='compliance_report',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='violation_category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]