# Generated by Django 6.1 on 2026-09-15 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_alter_complaint_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='evidence',
            field=models.ImageField(upload_to='complaint_evidence/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Submitted', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='violation_category',
            field=models.CharField(max_length=100),
        ),
    ]
