# Generated by Django 6.1.1 on 2026-09-16 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_alter_complaint_user'),
        ('products', '0004_extractedlabeldata labeled lines json'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='products.productscan'),
        ),
    ]
