# Generated by Django 6.1.1 on 2026-09-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_complaint_scan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='evidence',
        ),
    ]
