# Generated by Django 6.1.1 on 2026-09-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_remove_complaint_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='company_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='company_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('FORWARDED', 'Forwarded to Company'), ('RESPONDED', 'Initial Response from Company'), ('COMPLETED', 'Completion')], default='REGISTERED', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='violation_category',
            field=models.CharField(max_length=500),
        ),
    ]
