# Generated by Django 6.1.1 on 2026-09-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_complaint_company_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='initial_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='initial_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
