# Generated by Django 6.1.1 on 2026-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_remove_complaint_company_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
