# Generated by Django 6.1.1 on 2026-09-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_complaint_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='verification_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='verification_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('FORWARDED', 'Forwarded to Company'), ('RESPONDED', 'Initial Response from Company'), ('VERIFICATION', 'Verification'), ('COMPLETED', 'Completion')], default='REGISTERED', max_length=20),
        ),
    ]
